/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Asynchronously calls https://www.google.com and returns the response body as a string.
 *
 * This function uses the async reqwest client. When used via napi,
 * it will return a promise that resolves to the response text.
 */
export declare function callGoogle(): Promise<string>
